view:
  reload: true
  engine:
    "django" :
      path: "./application/views/"
      suffix: ".tpl"
    "html" :
      path: "./application/views/"
      suffix: ".html"
session:
  name: "gosessionid"
  expires: 0
port: 2018
pprof:
  open: false
  port: 6060
  route: "/debug/pprof/*action"
log_path: "logs"
charset: "UTF-8"
hashkey: "the-big-and-secret-fash-key-here"
blockkey: "lot-secret-of-characters-big-too"
backend_route_party: "/b/"
upload:
  engine: "oss" #oss or file
  base_path: "assets"

redis:
  host: "115.159.71.60:6379"
  connect_timeout: 2
  read_timeout: 4
  write_timeout: 4
  cache_database_index: 1
  session_database_index: 0
  password: "asd159"
  max_idle: 3
  max_active: 5
  idle_timeout: 60
