debug: true
port: 2019
view:
  reload: false
  fedirname: "./resources/themes/"
  bedirname: "./resources/views/"
  theme: "default"
session:
  name: "gosessionid"
  expires: 0

runtime_path: "runtime"
cache_db: "cache.db"
log_path: "logs"

plugin_enable: false
plugin_path: "plugins"

favicon: "./resources/assets/favicon.ico"
charset: "UTF-8"
jwtkey: "jwt_token_you_need_set_again"
hashkey: "the-big-and-secret-fash-key-here"  # 只支持固定大小到字节, AES only supports key sizes of 16, 24 or 32 bytes.
blockkey: "lot-secret-of-characters-big-too"
max_bodysize: 32 # MB

upload:
  engine: "oss" #oss or file
  base_path: "uploads" # 基本路径

statics:
  - { route: "/assets/", path: "./resources/assets/"}
  - { route: "/uploads/", path: "./resources/assets/uploads/"}


search:
  url: http://127.0.0.1:4080
  username: admin
  password: 123456
