view:
  reload: true
  engine:
    #    django :
    #      path: "./resources/views/"
    #      suffix: ".tpl"
    html:
      path: "./resources/views/"
      suffix: ".html"
session:
  name: "gosessionid"
  expires: 0
cache_db: "./runtime/cache/store.db"  # 包括session
port: 2019
pprof:
  open: true
  port: 6060
  route: "/debug/pprof/*action"
log_path: "./runtime/logs/"
favicon: "./resources/assets/favicon.ico"
charset: "UTF-8"
hashkey: "the-big-and-secret-fash-key-here"  # 只支持固定大小到字节, 妈的, 因为这个浪费了4个小时到时间找bug AES only supports key sizes of 16, 24 or 32 bytes.
blockkey: "lot-secret-of-characters-big-too"
backend_route_party: "/b/"
max_bodysize: 32 # MB
upload:
  engine: "oss" #oss or file
  base_path: "assets" # 基本路径

statics:
  - {route: "/assets", path: "./resources/assets"}

redis:
  host: "115.159.71.60:6379"
  connect_timeout: 2
  read_timeout: 4
  write_timeout: 4
  cache_database_index: 1
  session_database_index: 0
  password: ""
  max_idle: 3
  max_active: 5
  idle_timeout: 60
